-- MySQL Script generated by MySQL Workbench
-- Thu Jun 20 18:25:47 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Drop Schema dai-c3
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dai-c3` ;

-- -----------------------------------------------------
-- Create Schema dai-c3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dai-c3` DEFAULT CHARACTER SET utf8 ;
USE `dai-c3` ;

-- -----------------------------------------------------
-- Table `dai-c3`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dai-c3`.`usuario` ;

CREATE TABLE IF NOT EXISTS `dai-c3`.`usuario` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `apellido` VARCHAR(50) NOT NULL,
  `username` VARCHAR(10) NOT NULL,
  `pass` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `dai-c3`.`alumno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dai-c3`.`alumno` ;

CREATE TABLE IF NOT EXISTS `dai-c3`.`alumno` (
  `rut` VARCHAR(10) NOT NULL,
  `carrera` VARCHAR(50) NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`rut`),
  INDEX `FK_usuario_idx` (`id_usuario` ASC),
  CONSTRAINT `FK_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `dai-c3`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
